### ISSUE TITLE
Page refresh in middle of layout task

### ISSUE THREAD

**Issue by mwoodb** [BuddingMindsLab/Spatial_layout#4]
There was a full page refresh at one point in the 1st layout and in the 2nd, where the page went white and then all the images came back. I'm not sure why this would happen, but if we can figure it out it would be nice if that never happened. It might have just been my poor internet connection though, so maybe we should test this out (ask any RAs we get to do the task).

**Comment by mwoodb** [comment]
Related to this, which might be another symptom of my poor internet but still worth testing - sometimes the feedback sound was very delayed for when I got a card correct.

**Comment by DanielWurgaft** [comment]
I haven't experienced that, so could be the internet connection... (?)
